version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    networks:
      - api-card-network
    environment:
      POSTGRES_DB: cards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 120900m
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  api-card-network:

volumes:
  postgres_data:
    driver: local
