server:
  port: 0

spring:
  application:
    name: mscreditevaluator

eureka:
  client:
    service-url:
      defaultZone: http://mscard-eureka-user:rdc-eaa-eskmrreusu@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

mq:
  queues:
    card-issuance: card-issuance
